name: Sleep Pipeline

on:
  workflow_dispatch:

jobs:
  sleep:
    runs-on: my-docker-scale-set
    strategy:
      matrix:
        value: [one, two, three]
    steps:
      - name: Run shell script that prints matrix value
        shell: bash
        run: |
          echo "Matrix value: ${{ matrix.value }}"
          sleep 60